- targets:
  - "127.0.0.1:8080"
  labels:
    hostname: LocalHost
#- targets:
#  - "127.0.127.128:8080"
#  labels:
#    hostname: Server1
#- targets:
#  - "127.127.127.129:8080"
#  labels:
#    hostname: Server2
